apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/cse4100/kubernetes-custom-nginx:1.0
        resources:
          limits:
            memory: 16Mi
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: css-secret-web-server
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      location / {
        log_not_found off;
        error_log /var/log/nginx/error.log debug;
        location /public/ {
        auth_basic off;
      }
      location = /public/kube.png {
        auth_basic off;
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-auth
type: Opaque